nhsbsa/nhs-volunteering-beta-prototype

app/views/bsa-admin/check-answers.html

bsa-admin - content change on check-answers.html

---

app/views/bsa-admin/check-answers.html

bsa-admin/ - correction to link destination on check-answers

---

app/views/bsa-admin/check-answers.html

bsa-admin - change in content layout in check-answers.html

---

app/views/layout_vol_header.html
app/views/v1/application/address.html
app/views/v1/application/availability.html
app/views/v1/application/check.html
app/views/v1/application/choose-address.html
app/views/v1/application/dob.html
app/views/v1/application/email.html
app/views/v1/application/manual-address.html
app/views/v1/application/motivations.html
app/views/v1/application/name.html
app/views/v1/application/phone.html
app/views/v1/application/start.html
app/views/v1/application/submitted.html
app/views/v1/error-path/404.html
app/views/v1/error-path/no-results.html
app/views/v1/error-path/not-found.html
app/views/v1/error-path/outside-england.html
app/views/v1/form-errors/postcode-all-errors.html
app/views/v1/form-errors/postcode-invalid.html
app/views/v1/form-errors/postcode-missing.html
app/views/v1/form-errors/radius-missing.html
app/views/v1/homepage.html
app/views/v1/postcode-search.html
app/views/v1/results.html
app/views/v1/role-profile-1.html
app/views/v1/role-profile-2.html
app/views/v1/trust-redirect.html
app/views/v1/view-types.html
app/views/v1/what-its-like.html

Volunteer testing

---

app/views/v1/application/check.html
app/views/v1/application/motivations.html
app/views/v1/application/submitted.html
app/views/v1/results.html
app/views/v1/role-profile-1.html
app/views/v1/trust-redirect.html

Content updates - post content 2i

---

app/views/index.html
app/views/v1/application/address.html
app/views/v1/application/email.html
app/views/v1/form-errors/choose-address-not-selected.html
app/views/v1/form-errors/email-missing.html
app/views/v1/form-errors/email-not-match.html
app/views/v1/form-errors/enter-address-missing.html
app/views/v1/form-errors/find-address-invalid-postcode.html
app/views/v1/form-errors/find-address-missing.html
app/views/v1/form-errors/name-missing.html
app/views/v1/form-errors/phone-not-input.html
app/views/v1/form-errors/phone-not-selected.html
app/views/v1/sub-index-bsa.html
app/views/v1/sub-index-rec.html
app/views/v1/sub-index-vol.html

- Added personal details errors
- Added sub-index pages for each strand of work to track progress
- Made a change to find address button to reflect UR insight

Personal details

---

app/views/v1/sub-index-bsa.html
app/views/v1/sub-index-vol.html

corrections to sub-index-bsa and sub-index-vol links

---

app/views/v1/meet-our-volunteers.html

v1/meet-our-volunteers.html - correction to typo in link text

---

app/views/v1/error-path/address-not-found.html
app/views/v1/sub-index-vol.html

- Added no address found error path

Add no address found error

---

app/views/v1/application/phone.html
app/views/v1/form-errors/find-address-invalid-postcode.html
app/views/v1/form-errors/phone-not-input.html
app/views/v1/form-errors/phone-not-selected.html

- Changed content flagged in 2i checks

Content 2i

---

app/views/v2/role-categories/admin.html
app/views/v2/role-categories/charity.html
app/views/v2/role-categories/clinical.html
app/views/v2/role-categories/community.html
app/views/v2/role-categories/leisure.html
app/views/v2/role-categories/patient-facing.html
app/views/v2/role-categories/ppe.html
app/views/v2/role-categories/remote.html
app/views/v2/role-categories/view-types.html
app/views/v2/role-categories/young-person.html
app/views/v2/volunteering/index.html

Role category content

---

app/assets/sass/main.scss
app/views/v2/volunteering/meet-our-volunteers.html
app/views/v2/volunteering/what-its-like.html

Content changes

---

app/views/v2/volunteering/results.html
app/views/v2/volunteering/role-profile-2.html
app/views/v2/volunteering/role-profile-4.html
app/views/v2/volunteering/trust-redirect.html

- Changed multiple location result based on what can be achieved technically
- Added a multiple location listing page
- Changed summary format on generic role listing
- Added useful info box to other listings

Tech changes needed for search and listings

---

app/views/v2/volunteering/what-its-like.html

v2/what-its-like.html - styling/margin to quote cards

---

app/views/v2/application/start-external.html
app/views/v2/volunteering/results.html
app/views/v2/volunteering/role-profile-5.html

- Added a 5th role profile for a third party application
- Added start page for third party applications

External start page added

---

app/views/v2/application/dob.html
app/views/v2/application/name.html

v2/ - changes to correct link destinations

---

app/views/v2/application/name.html
app/views/v2/application/start.html

v2/ correction to link destinations part 2

---

app/views/bsa-admin/confirmation-page.html

bsa-admin/ changes to content /next steps on confirmation-page.html

---

app/views/v1/form-errors/find-address-invalid-postcode.html

v1/form-errors - edit to error message language, from valid to real

---

app/views/v3/volunteering/meet-our-volunteers.html
app/views/v3/volunteering/what-its-like.html

v3/ what-its-like & meet-vols content updates

---

app/views/v3/application/age.html
app/views/v3/volunteering/meet-our-volunteers.html
app/views/v3/volunteering/what-its-like.html

What its like emma

---

app/views/v1/sub-index-vol.html
app/views/v3/application/age.html
app/views/v3/application/check.html
app/views/v3/form-errors/check-not-selected.html

Check your answers and age update

---

app/views/v3/application/check.html

v3/ check.html - minor content change for age range

---

app/views/v3/application/check.html

v3/ removal of range in age range on check.html

---

app/views/bsa-admin/details-character-limits.html
app/views/bsa-admin/telephone-error.html

bsa-admin/ changes to error screens

---

app/views/v1/sub-index-vol.html
app/views/v3/form-errors/phone-character-limit.html
app/views/v3/form-errors/phone-character-valid.html

Changed telephone number question to new design

Telephone number redesign

---

app/views/r2/index.html
app/views/r2/manage-listing/manage-closed.html
app/views/r2/manage-listing/manage-draft.html
app/views/r2/manage-listing/manage-live-external.html
app/views/r2/manage-listing/manage-live.html
app/views/r2/manage-listing/preview.html

Added dashboard and ability to manage listings (draft, live and closed)

Manage dashboard

---

app/routes.js
app/views/r2/opportunity-name.html
app/views/r2/questions/address.html
app/views/r2/questions/another-location.html
app/views/r2/questions/choose-address.html
app/views/r2/questions/contact-details-change.html
app/views/r2/questions/contact-details.html
app/views/r2/questions/create-an-opportunity.html
app/views/r2/questions/looking-for.html
app/views/r2/questions/new-name.html
app/views/r2/questions/overview-process.html
app/views/r2/questions/preview.html
app/views/r2/questions/recieve-applications.html
app/views/r2/questions/reference-number.html
app/views/r2/questions/remote.html
app/views/r2/questions/summary.html
app/views/r2/questions/support-volunteers.html
app/views/r2/task-list-fixed.html
app/views/v1/sub-index-vol.html
app/views/v3/volunteering/what-its-like.html

R2 create a role

---

app/views/r2/manage-listing/manage-live-external.html
app/views/r2/manage-listing/manage-live.html

Listing urls

---

app/views/r2/questions/create-an-opportunity.html
app/views/r2/questions/looking-for.html
app/views/r2/questions/overview-process.html
app/views/r2/questions/preview.html
app/views/r2/start-page.html

Create a role   fs

---

app/views/bsa-admin/confirmation-page.html

bsa / change to confirmation.html content

---

app/views/r2/errors/500-error.html
app/views/r2/errors/name-field-empty.html
app/views/v1/sub-index-rec.html

Added a 404 not found for volunteer journey
Added a general service down error for recruiter side
Added an example error for create a role

Error pages

---

app/views/r3/opportunity-name.html
app/views/r3/questions/contact-details.html
app/views/r3/questions/looking-for.html
app/views/r3/questions/preview.html
app/views/r3/questions/support-volunteers.html
app/views/r3/start-page.html
app/views/r3/task-list-fixed.html

V3 create a role francesca

---

app/views/v3/role-categories/admin.html
app/views/v3/role-categories/charity.html
app/views/v3/role-categories/clinical.html
app/views/v3/role-categories/community.html
app/views/v3/role-categories/leisure.html
app/views/v3/role-categories/patient-facing.html
app/views/v3/role-categories/ppe.html
app/views/v3/role-categories/remote.html
app/views/v3/role-categories/view-types.html
app/views/v3/role-categories/young-person.html
app/views/v3/volunteering/role-profile-blank.html
app/views/v4/application/availability.html
app/views/v4/application/check.html
app/views/v4/application/choose-address.html
app/views/v4/application/email.html
app/views/v4/application/motivations.html
app/views/v4/application/phone.html
app/views/v4/application/support.html
app/views/v4/role-categories/admin.html
app/views/v4/role-categories/charity.html
app/views/v4/role-categories/clinical.html
app/views/v4/role-categories/community.html
app/views/v4/role-categories/leisure.html
app/views/v4/role-categories/patient-facing.html
app/views/v4/role-categories/ppe.html
app/views/v4/role-categories/remote.html
app/views/v4/role-categories/view-types.html
app/views/v4/role-categories/young-person.html
app/views/v4/volunteering/role-profile-blank.html

V4 accessibility testing

---

app/routes.js
app/views/r3/questions/alt-closing-date-answer.html
app/views/r3/questions/alt-closing-date.html
app/views/r3/questions/recieve-applications.html

r3/ addition of files for alt-closing date plus its routing

---

app/views/r3/opportunity-name.html
app/views/r3/questions/availability.html
app/views/r3/questions/looking-for.html
app/views/r3/questions/preview.html
app/views/r3/start-page.html
app/views/r3/task-list-fixed.html

Francesca's edits to create a role

---

app/views/index.html
app/views/r3/are-you-sure-delete.html
app/views/r3/dashboard-deleted.html
app/views/r3/dashboard-success.html
app/views/r3/task-list-completed.html
app/views/v1/sub-index-rec.html

Section 1 changes

---

app/views/r3/close-listing-now.html
app/views/r3/index.html
app/views/r3/manage-listing/manage-application.html
app/views/r3/manage-listing/manage-closed.html
app/views/r3/manage-listing/manage-draft.html
app/views/r3/manage-listing/manage-live.html
app/views/r3/task-list-fixed.html

Manage application/listing iterations

---

app/views/r3/manage-listing/manage-draft.html
app/views/r3/questions/availability.html
app/views/r3/questions/looking-for.html

r3/ content updates to avaialbility and related pages

---

app/views/r3/opportunity-name.html
app/views/r3/task-list-fixed.html

Heading sizes

---

app/views/r3/questions/check-listing.html
app/views/r3/start-page.html
app/views/v4/application/check.html
app/views/v4/application/choose-address.html
app/views/v4/application/manual-address.html

R3 emma changes

---

app/views/r3/dashboard-deleted.html
app/views/r3/start-page.html

r3/ chunk 1 content changes

---

app/routes.js
app/views/r3/errors/name-field-empty.html
app/views/r3/preview.html
app/views/r3/questions/recieve-applications.html
app/views/r3/task-list-completed.html

Handover changes

---

app/views/r3/questions/address.html

r3/ content change on address.html

---

app/views/r3/questions/preview.html
app/views/r3/questions/summary.html
app/views/r3/questions/support-volunteers.html

r3/ word count amendments, copy changes

---

app/views/r3/questions/availability.html

r3/ updates character count on availability.html

---

app/views/r3/questions/contact-details.html
app/views/r3/questions/overview-process.html
app/views/r3/questions/preview.html
app/views/v5/results.html
app/views/v5/terms-conditions.html

Recruiter emma changes

---

app/views/r3/errors/alt-closing-date-select-one.html
app/views/r3/questions/alt-closing-date.html

r3/ copy changes to closing date, incl error page

---

app/views/r3/errors/remote-empty.html
app/views/r3/questions/remote.html

r3/ - content updates, incl on error counterpart

---

app/views/v5/cookies.html
app/views/v5/privacy-policy.html
app/views/v5/recruiters-terms-conditions.html
app/views/v5/terms-conditions.html

v5/ cookie, policy, terms page updates, including link href destinations

---

app/views/r3/errors/overview-process-empty.html
app/views/r3/errors/overview-process-over-character-count.html
app/views/r3/questions/overview-process.html
app/views/v3/volunteering/role-profile-1.html

r3/ copy changes for preview & associated error pages

---

app/views/v4/recruiters-terms-conditions.html

New footer policies   fs

---

app/views/r3/errors/recieve-applications-https.html
app/views/r3/errors/recieve-applications-over-character-count.html
app/views/v1/sub-index-rec.html

r3/ recruiter error pages fore receieve-applications.html

---

app/views/v4/recruiters-terms-conditions.html

Footer policies sprint 10

---

app/views/v5/index-cookies-accepted.html
app/views/v5/index-cookies-declined.html
app/views/v5/index-cookies.html

v4/ addition of correct href destinations

---

app/assets/sass/main.scss
app/views/v4/cookies-saved.html
app/views/v5/index-cookies-declined.html
app/views/v5/index.html

v4/ save cookies file

---

app/views/v4/recruiters-terms-conditions.html

v4/ content update to anonymised

---

app/assets/sass/main.scss
app/routes.js
app/views/r3/index.html
app/views/r3/questions/check-listing.html
app/views/r3/task-list-section-1-completed.html
app/views/v1/sub-index-vol.html
app/views/v5/index-feedback.html

Added a feedback banner, changed some tasklist behaviour and updated the index pages

Feedback banner and index updates

---

app/views/r3/task-list-section-1-completed.html

r3/ url changes for half-completed task list

---

app/views/bsa-admin/service-error.html
app/views/r4/errors/500-error.html

Sprint11 francesca

---

app/views/bsa-admin/email-link-expired.html

EA - closing bracket for a tag in bsa-admin error file

---

app/views/v4/privacy-policy.html
app/views/v4/recruiters-terms-conditions.html
app/views/v4/terms-conditions.html

Sprint 12 francesca

---

app/views/v4/privacy-policy.html
app/views/v4/recruiters-terms-conditions.html

Sprint12 fran

---

app/routes.js
app/views/v5/edi/background-arab.html
app/views/v5/edi/background-asian.html
app/views/v5/edi/background-black.html
app/views/v5/edi/background-mixed-multiple.html
app/views/v5/edi/background-white.html
app/views/v5/edi/day-activities.html
app/views/v5/edi/dob.html
app/views/v5/edi/equality-questions.html
app/views/v5/edi/ethnic-group.html
app/views/v5/edi/gender-identity.html
app/views/v5/edi/health-conditions.html
app/views/v5/edi/religion.html
app/views/v5/edi/sex.html
app/views/v5/edi/sexual-orientation.html

Edi questions emma

---

app/views/v5/edi/day-activities.html
app/views/v5/edi/ethnic-group.html
app/views/v5/edi/religion.html
app/views/v5/edi/sex.html

v5/edi/ tidy-up of link destinations, id/names

---

app/views/v5/edi/background-asian.html
app/views/v5/edi/religion.html

v5/edi content tidyup (capitals, etc), missing hint text

---

app/views/v5/edi/ethnic-group.html
app/views/v5/edi/religion.html
app/views/v5/edi/sexual-orientation.html

v5/edi - content updates

---

app/views/v5/edi/background-white.html
app/views/v5/edi/dob.html
app/views/v5/edi/ethnic-group.html
app/views/v5/edi/gender-identity.html
app/views/v5/edi/sex.html
app/views/v5/edi/sexual-orientation.html

v5/edi - content changes, label tidy-ups

---

app/views/v4/recruiters-terms-conditions.html

New sprint12 francesca

---

app/views/v4/cookies.html

Cookie changes

---

app/views/v5/edi/errors/background-mixed-multiple.html
app/views/v5/edi/errors/day-activities.html
app/views/v5/edi/errors/equality-questions.html
app/views/v5/edi/errors/ethnic-group.html
app/views/v5/edi/errors/gender-identity.html
app/views/v5/edi/errors/health-conditions.html
app/views/v5/edi/errors/religion.html
app/views/v5/edi/errors/sex.html
app/views/v5/edi/errors/sexual-orientation.html

EDI error messages

---

app/views/r9/edit-journey/check-listing-edit.html
app/views/r9/edit-journey/closing-date-answer-edit.html
app/views/r9/edit-journey/republish-listing-dashboard-success.html
app/views/r9/edit-journey/task-list-completed.html
app/views/r9/preview.html
app/views/r9/questions/check-listing.html
app/views/sub-index-rec.html
app/views/v9/volunteering/index-emergency-volunteering.html

Emergency volunteering homepage copy updated

---

app/views/r9/edit-journey/application-limit-edit.html
app/views/r9/edit-journey/closing-date-answer-edit.html

H1 changes to edit flow

---

app/views/r9/edit-journey/task-list-completed.html
app/views/r9/questions/support-volunteers.html

H1 changes to edit task list

---

app/views/v9/volunteering/index-emergency-volunteering.html

emergency volunteering link update

---

app/views/v9/role-categories/view-types.html

Changing padding and margins between cards for opportunities types page for SEO

---

app/views/r9/dashboard-success.html
app/views/r9/edit-journey/closing-date-choice-edit.html
app/views/r9/edit-journey/closing-date-edit.html
app/views/r9/edit-journey/task-list-completed.html

Updates to closing date H1 and radios + survey link copy on listing published

---

app/views/v9/index-feedback.html

layout bug fixed on volunteering feedback banner page

---

app/views/r9/edit-journey/republish-listing-dashboard-success.html
app/views/r9/manage-listing/reuse-listing-dashboard-success.html

Updated re-published success and reuse listing success screens to have survey link

---

app/views/r9/manage-listing/questions/check-listing.html
app/views/r9/questions/listing-dashboard-success.html

listing published success survey link

---

app/views/r9/edit-journey/republish-listing-dashboard-success.html

edit to copy for edit listing survery

---

app/views/r9/edit-journey/republish-listing-dashboard-success.html

Edit to dashboard hyperlinks on edit listing success screen

---

app/views/sub-index-vol.html
app/views/v9/role-categories/view-types-v3.html

v3 of opportunity types screen with remote, combining companionship & clinical care

---

app/views/r9/edit-journey/closing-date-changes-confirmation.html
app/views/r9/edit-journey/closing-date-choice-edit.html
app/views/r9/edit-journey/closing-date-edit.html
app/views/r9/questions/alt-closing-date.html
app/views/r9/questions/closing-date-changes-confirmation.html

Adding in a confirmation screen for edit the closing date flow

---

app/views/v9/application/submitted.html
app/views/v9/results/results-v2.html

V9 changes - changing back to original v9

---

app/views/v9/role-categories/patient-facing.html

Update patient facing with KJ comments

---

app/views/gds/role-categories/admin.html
app/views/gds/role-categories/charity.html
app/views/gds/role-categories/clinical.html
app/views/gds/role-categories/remote.html

changes to images for role categories / view types pages 

---

app/views/gds/application/submitted.html
app/views/gds/edi/equality-questions-skip.html
app/views/gds/edi/equality-questions-submitted.html
app/views/gds/results/results_page_2.html
app/views/gds/results/results_page_3.html
app/views/gds/volunteering/postcode-search.html
app/views/gds/volunteering/role-profile-0.html
app/views/gds/volunteering/role-profile-1.html
app/views/gds/volunteering/role-profile-2.html
app/views/gds/volunteering/role-profile-3.html
app/views/gds/volunteering/role-profile-4.html
app/views/gds/volunteering/role-profile-5.html
app/views/gds/volunteering/role-profile-blank.html
app/views/gds/volunteering/role-profile-canine-befriender copy.html
app/views/gds/volunteering/role-profile-canine-befriender.html
app/views/gds/volunteering/role-profile-driver.html
app/views/gds/volunteering/taking-you-to-the-organisations-website.html

Replaced results page to reflect changes for GDS recommendations

Replaced results with results v2 for GDS recommendations

---

app/assets/sass/main.scss
app/views/gds/volunteering/index-v2.html

changes to v2 index page - based on mockup example

changes to v2 index page

---

app/views/gds/application/submitted.html
app/views/r10/dashboard-update-option-1-mvp/changing-status-flow/manage-application-1-reviewed.html
app/views/r10/dashboard-update-option-1-mvp/changing-status-flow/manage-live-archived-2.html
app/views/r10/dashboard-update-option-1-mvp/changing-status-flow/manage-live-new.html
app/views/r10/dashboard-update-option-1-mvp/changing-status-flow/manage-live-reviewed.html
app/views/r10/dashboard-update-option-1-mvp/manage-live-archived.html
app/views/r10/dashboard-update-option-1-mvp/manage-live.html

Service scope extension changes from product time / GDS updates

---

app/views/index.html
app/views/v11/role-categories/view-types.html
app/views/v11/volunteering/index.html
app/views/v11/volunteering/meet-our-volunteers.html

Creation of v11 - gds changes post usability testing
- Added homepage with banner and segmented image cards
- Fixed links for 'other ways you can help the NHS' on the 'hope you can help' page as well as linking 'go back' on that page

Creation of v11 - gds changes post usability testing

---

app/views/v11/results/results-v2.html

Updates to content on filters for search results
